(function() {var implementors = {};
implementors["bench_configure"] = [{"text":"impl Args for <a class=\"struct\" href=\"bench_configure/struct.DistributedBenchmarkConfigurator.html\" title=\"struct bench_configure::DistributedBenchmarkConfigurator\">DistributedBenchmarkConfigurator</a>","synthetic":false,"types":["bench_configure::DistributedBenchmarkConfigurator"]}];
implementors["remote_load_generator"] = [{"text":"impl Args for <a class=\"struct\" href=\"remote_load_generator/struct.DistributedBenchmark.html\" title=\"struct remote_load_generator::DistributedBenchmark\">DistributedBenchmark</a>","synthetic":false,"types":["remote_load_generator::DistributedBenchmark"]}];
implementors["rpc_server"] = [{"text":"impl Args for <a class=\"struct\" href=\"rpc_server/struct.RpcGatewayOpt.html\" title=\"struct rpc_server::RpcGatewayOpt\">RpcGatewayOpt</a>","synthetic":false,"types":["rpc_server::RpcGatewayOpt"]}];
implementors["sui"] = [{"text":"impl Args for <a class=\"struct\" href=\"sui/benchmark/bench_types/struct.Benchmark.html\" title=\"struct sui::benchmark::bench_types::Benchmark\">Benchmark</a>","synthetic":false,"types":["sui::benchmark::bench_types::Benchmark"]},{"text":"impl Args for <a class=\"struct\" href=\"sui/wallet_commands/struct.WalletOpts.html\" title=\"struct sui::wallet_commands::WalletOpts\">WalletOpts</a>","synthetic":false,"types":["sui::wallet_commands::WalletOpts"]}];
implementors["sui_move"] = [{"text":"impl Args for <a class=\"struct\" href=\"sui_move/struct.MoveOpt.html\" title=\"struct sui_move::MoveOpt\">MoveOpt</a>","synthetic":false,"types":["sui_move::MoveOpt"]}];
implementors["validator"] = [{"text":"impl Args for <a class=\"struct\" href=\"validator/struct.ValidatorOpt.html\" title=\"struct validator::ValidatorOpt\">ValidatorOpt</a>","synthetic":false,"types":["validator::ValidatorOpt"]}];
implementors["wallet"] = [{"text":"impl Args for <a class=\"struct\" href=\"wallet/struct.ClientOpt.html\" title=\"struct wallet::ClientOpt\">ClientOpt</a>","synthetic":false,"types":["wallet::ClientOpt"]}];
implementors["x"] = [{"text":"impl Args for <a class=\"struct\" href=\"x/lint/struct.Args.html\" title=\"struct x::lint::Args\">Args</a>","synthetic":false,"types":["x::lint::Args"]},{"text":"impl Args for <a class=\"struct\" href=\"x/struct.Args.html\" title=\"struct x::Args\">Args</a>","synthetic":false,"types":["x::Args"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()